development:
  sessions:
    default:
      database: quake_map_development
      hosts:
        - localhost:27017
  options:
    include_root_in_json: false
    use_activesupport_time_zone: true

production:
  sessions:
    default:
      database: quake_map_production
      hosts:
        - localhost:27017
  options:
    include_root_in_json: false
    use_activesupport_time_zone: true

test:
  sessions:
    default:
      database: quake_map_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
